### ISSUE TITLE
Wir benötigen einen separaten Bauteiltyp-Code und Bauteiltyp für „E-Ladesäulen“

### ISSUE THREAD

**Issue by JensNeffe** [CAFM-Connect/CAFM-Connect#110]
Derzeit werden die Anlagenart 449 Starkstromanlagen, sonstiges und 549 Technische Anlagen in Außenanlagen durch uns für E- Ladesäulen genutzt: wir benötigen einen separaten Bauteiltyp-Code und Bauteiltyp für „E-Ladesäulen“.

- [x] 449.10 > Stromart > Gleichstrom, Wechselstrom
- [x] 449.10 > maximale Ladeleistung (kW)
- [x] 449.10 > Anzahl Ladepunkte
- [x] 449.10 > Typ Ladesäule >  (normal, schnell, hypercharging)
- [x] 449.10 > Steckertyp > (Typ 1, Typ 2, CCS Combo 2)
- [x] 449.10 > Aufstellart > (Wand, frei stehend)
- [x] 449.10 > Messeinrichtung > (eichrechtskonform, nicht eichrechtskonform)
- [x] 449.10 > Bezahleinrichtung > (ja/nein)
- [x] 449.10 > Sicherheitskommunikationseinrichtung > (ja/nein)
----- Klären, ob diese Felder allen Bauteilen (der 400er) zugeordnet werden können und dann vererbt werden könnten:
- [ ] 449.10 > Koordinate
- [x] 449.10 > Hersteller
- [ ] 449.10 > Herstellertyp
- [x] 449.10 > Baujahr
- [ ] 449.10 > Inbetriebnahmedatum

**Comment by ottoxt** [comment]
Die übergeordneten Merkmale sind an anderer Stelle behandelt. Kann daher geschlossen werden.
