### ISSUE TITLE
Als Erfasser von Daten möchte ich das Attribut "DiBT-Zulassungsnummer" anpassen (334.10 ud 344.10)

### ISSUE THREAD

**Issue by RSR001** [CAFM-Connect/CAFM-Connect#13]
Bezeichnung muss lauten "DIBt"
Datentyp muss Text sein, da Kombination von Buchstaben und Zahlen

**Comment by ottoxt** [comment]
Der Datentyp lässt sich nicht ändern. Bug in bimeta?
