### ISSUE TITLE
Enumerationswerte, die an mehreren Klassen vorgekommen sind, scheinen mehrfach importiert worden zu sein

### ISSUE THREAD

**Issue by ottoxt** [CAFM-Connect/CAFM-Connect#14]
Hier Beispiel Feuerwiderstandsklasse:

![image](https://user-images.githubusercontent.com/1270288/198064039-8b58e30d-babd-47af-8179-76aa0597e598.png)

**Comment by wolkenflitzersjanse** [comment]
fixed

**Comment by ottoxt** [comment]
Beim schnellen Durchsehen habe ich noch einmal was gesehen, so dass ich mich entschlossen habe, das noch mal zu checken.
