### ISSUE TITLE
Die Klasse "Bäume" wurde von der KG 547.10 in die KG 573.10 verschoben. Dabei wurden einige Untergruppen entfernt.

### ISSUE THREAD

**Issue by vlaregon** [CAFM-Connect/CAFM-Connect#55]
Die Klasse "547.10 Bäume" hat folgende Untergruppen enthalten:
- "547.10 Kronen"
- "547.10 Stämme"
- "547.10 Kronensicherung"
- "547.10 Nistkästen"
In der neuen Gruppe "573.10 Bäume" sind zwei ersten Untergruppen nicht mehr vorhanden. Gibt es einen Grund dafür?

**Comment by ottoxt** [comment]
Kronen und Stämme haben wir mit dem Import entfernt, weil das in der Praxis so nicht erfasst wird und auch in der Norm (FLL-Baumkontrollrichtlnie) anders vorgegeben ist.
Der Baum ist in der neuen Version unter 573.10 aufgeführt. Nistkästen und Kronensicherungen sind eigene Bauteile 573.16 - Nistkästen und 573.15 - Kronensicherungen.
